apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  type: LoadBalancer
  ports:
    - port: 80        # external LB port
      targetPort: 8080  # Spring Boot port
  selector:
    app: spring-app
